require_relative "../response"

module SerpApi
  module Duckduckgo
    class Search
      private attr_reader :query, :api_key

      def initialize(query, api_key:)
        @query = query
        @api_key = api_key
      end

      # Note: I can't list all the possible keys inside facts
      # because some are autogenerated (like "born").
      def knowledge_graph = Data.define(:facts)[**body["knowledge_graph"].slice("facts")]

      private

        def body
          @body ||= SerpApi::Response.new(params.to_h).to_h
        end

        def params = { q: query.to_s, api_key:, engine: "duckduckgo" }
    end
  end
end
