require_relative "../response"

module SerpApi
  module Yahoo
    class Search
      private attr_reader :query, :api_key

      def initialize(query, api_key:)
        @query = query
        @api_key = api_key
      end

      def organic_results
        body["organic_results"].map { Data.define(:link)[**_1.slice("link")] }
      end

      # Note: I can't list all the possible keys because some are autogenerated (like "born").
      def knowledge_graph = body["knowledge_graph"]

      private

        def body
          @body ||= SerpApi::Response.new(params).to_h
        end

        def params = { p: query, api_key:, engine: "yahoo" }
    end
  end
end
